using Hazzik.Annotations;

namespace Hazzik.Chat
{
    [UsedImplicitly(ImplicitUseFlags.Initialize)]
    public enum ChannelNotification : byte
    {
        PlayerJoined = 0x00,
        PlayerLeft = 0x01,
        YouJoined = 0x02,
        YouLeft = 0x03,
        WrongPassword = 0x04,
        NotOnChannel = 0x05,
        NotModerator = 0x06,
        PasswordChanged = 0x07,
        OwnerChanged = 0x08,
        PlayerNotOnChannel = 0x09,
        NotOwner = 0x0A,
        CurrentOwner = 0x0B,
        Mute = 0x0C,
        Moderator = 0x0C,
        Announcing = 0x0D,
        NotAnnouncing = 0x0E,
        Moderated = 0x0F,
        NotModerated = 0x10,
        YouAreMuted = 0x11,
        Kicked = 0x12,
        YouAreBanned = 0x13,
        Banned = 0x14,
        Unbanned = 0x15,
        AlreadyOnChannel = 0x17,
        BeenInvitedToChannel = 0x18,
        InviteWrongFaction = 0x19,
        WrongAlliance = 0x1A,
        InvalidChannelName = 0x1B,
        ChannelIsNotModerated = 0x1C,
        HaveInvitedToChannel = 0x1D,
        CannotInviteBannedPlayer = 0x1E,
        ChatThrottledNotice = 0x1F,
        NotInCorrectAreaForChannel = 0x20,
        NotInLFGQueue = 0x21,
        VoiceEnabled = 0x22,
        VoiceDisabled = 0x23,
    }

    [UsedImplicitly(ImplicitUseFlags.Initialize)]
    public enum MessageType
    {
        Addon = -1,
        System = 0,
        Say = 1,
        Party = 2,
        Raid = 3,
        Guild = 4,
        Officer = 5,
        Yell = 6,
        Whisper = 7,
        WhisperForeign = 8,
        WhisperInform = 9,
        Emote = 10,
        TextEmote = 11,
        MonsterSay = 12,
        MonsterParty = 13,
        MonsterYell = 14,
        MonsterWhisper = 15,
        MonsterEmote = 16,
        Channel = 17,
        ChannelJoin = 18,
        ChannelLeave = 19,
        ChannelList = 20,
        ChannelNotice = 21,
        ChannelNoticeUser = 22,
        AFK = 23,
        DND = 24,
        Ignored = 25,
        Skill = 26,
        Loot = 27,
        Money = 28,
        Opening = 29,
        TradeSkills = 30,
        PetInfo = 31,
        CombatMiscInfo = 32,
        CombatXpGain = 33,
        CombatHonorGain = 34,
        CombatFactionChange = 35,
        BgSystemNeutral = 36,
        BgSystemAlliance = 37,
        BgSystemHorde = 38,
        RaidLeader = 39,
        RaidWarning = 40,
        RaidBossEmote = 41,
        RaidBossWhisper = 42,
        Filtered = 43,
        Battleground = 44,
        BattlegroundLeader = 45,
        Restricted = 46,
        BattleNet = 47,
        Achievement = 48,
        GuildAchievement = 49,
        ArenaPoints = 50,
        PartyLeader = 51
    }
}