using System;

namespace Hazzik.Items {
	public enum InventoryTypes {
		None = 0,
		Head = 1,
		Neck = 2,
		Shoulder = 3,
		Shirt = 4,
		Chest = 5,
		Waist = 6,
		Legs = 7,
		Feet = 8,
		Wrist = 9,
		Hands = 10,
		Finger = 11,
		Trinket = 12,
		Weapon = 13,
		Shield = 14,
		Ranged = 15,
		Back = 16,
		TwoHanded = 17,
		Bag = 18,
		Tabard = 19,
		Robe = 20,
		WeaponMainHand = 21,
		WeaponOffHand = 22,
		Holdable = 23,
		Ammo = 24,
		Thrown = 25,
		RangedRight = 26,
		Quiver = 27,
		Relic = 28,
	}
}