using System;

namespace Hazzik.Items {
	public enum ItemModType {
		Mana = 0,
		Health = 1,
		Agility = 3,
		Strength = 4,
		Intellect = 5,
		Spirit = 6,
		Stamina = 7,
		DefenseRating = 12,
		DodgeRating = 13,
		ParryRating = 14,
		ShieldBlockRating = 15,
		MeleeHitRating = 16,
		RangedHitRating = 17,
		SpellHitRating = 18,
		MeleeCriticalStrikeRating = 19,
		RangedCriticalStrikeRating = 20,
		SpellCriticalStrikeRating = 21,
		MeleeHitAvoidanceRating = 22,
		RangedHitAvoidanceRating = 23,
		SpellHitAvoidanceRating = 24,
		MeleeCriticalAvoidanceRating = 25,
		RangedCriticalAvoidanceRating = 26,
		SpellCriticalAvoidanceRating = 27,
		MeleeHasteRating = 28,
		RangedHasteRating = 29,
		SpellHasteRating = 30,
		HitRating = 31,
		CriticalStrikeRating = 32,
		HitAvoidanceRating = 33,
		CriticalAvoidanceRating = 34,
		ResilienceRating = 35,
		HasteRating = 36,
		ExpertiseRating = 37,
	}
}